A5
sree314/stepcvt pull request #21
Opened 2023-10-25 19:31 UTC by Asai-Yume

I still have some issues which seem to be some errors with the functions in partinfo, so I do not want to close the issue just yet

2023-10-25 20:15 UTC, sree314 requested changes
I think the code has too much Windows-specific stuff like drive names.

2023-10-25 20:15 UTC, sree314 commented on stepcvt/project.py
> +            path = PurePosixPath(path).relative_to("C:" / root)
This assumes a Windows system. I think you can just do relative_to (root)

2023-10-25 20:15 UTC, sree314 commented on stepcvt/project.py
> +                "path": str(path).replace("\\", "/"),
Not sure why you're doing this?

2023-10-25 20:15 UTC, sree314 commented on stepcvt/project.py
> +            path = Path("C:" / root / self["path"])
Windows-specific.

2023-10-25 20:15 UTC, sree314 commented on tests/test_cadsource.py
> +    x = CADSource(name="Rapido Hotend", path=Path("C:/tmp/abc/xyz.step"))
Don't change this.

2023-10-25 20:15 UTC, sree314 commented on tests/test_cadsource.py
> +    x = CADSource(name="Rapido Hotend", path=Path("C:/tmp/abc/xyz.step"))
Windows-specific change.

2023-10-25 20:15 UTC, sree314 commented on tests/test_cadsource.py
> +    assert str(cs.path).replace("\\", "/") == "C:/tmp/abc/xyz.step" # modified to accomodate windows path
Maybe look at Pathlib to figure out if there's a way to encode portable paths?

2023-10-26 16:09 UTC, Asai-Yume commented
> I think the code has too much Windows-specific stuff like drive names. 

If I remove the codes to accomodate the windows system, the tests wouldn't pass. Should we allow some sort of parameters to modify the paths? Or is there something I'm missing here?

2023-10-26 16:48 UTC, sree314 commented
Use the `as_posix` function for the slashes. I think removing the drive is necessary, not sure why it doesn't get removed in to_relative(). I think the tests may need some modifications, but reading Pathlib documentation may provide some better ideas that don't result in Windows- or Linux-specific code.

2023-10-26 21:41 UTC, Asai-Yume commented
> Use the `as_posix` function for the slashes. I think removing the drive is necessary, not sure why it doesn't get removed in to_relative(). I think the tests may need some modifications, but reading Pathlib documentation may provide some better ideas that don't result in Windows- or Linux-specific code.

2023-10-26 22:04 UTC, Asai-Yume commented
> Use the `as_posix` function for the slashes. I think removing the drive is necessary, not sure why it doesn't get removed in to_relative(). I think the tests may need some modifications, but reading Pathlib documentation may provide some better ideas that don't result in Windows- or Linux-specific code.

Yes, using the as_posix function did resolve the problems for slashes. I think what needed to be done is using a PurePath object rather than a Path object. Though I'm still unsure what to do with the from_dict function, since I'm manually padding a drive to the path for windows users, and I do not see functions in the documentation that does that.

2023-10-27 00:25 UTC, sree314 commented on stepcvt/project.py
> +            path = Path("C:" / root / self["path"])
I think you can remove the drive here, since it'll be present in root if needed.

2023-10-27 00:25 UTC, sree314 commented on stepcvt/project.py
> +                path = path.relative_to(drive / root)
This will not produce relative paths on Unix-like systems.

2023-10-27 00:27 UTC, sree314 commented
Don't add C: -- that's wrong even on Windows when multiple drives are used.

2023-10-27 13:28 UTC, sree314 commented on tests/test_cadsource.py
> +    x = CADSource(name="Rapido Hotend", path=Path("C:/tmp/abc/xyz.step"))
I've been thinking about this, and I think we need two tests -- one for Unix-like systems and another for Windows-like systems. The Windows tests can add a drive letter, etc.

2023-10-27 13:28 UTC, sree314 commented on tests/test_cadsource.py
> +    assert str(cs.path).replace("\\", "/") == "C:/tmp/abc/xyz.step" # modified to accomodate windows path
This would also go into the Windows specific test.

2023-11-06 14:12 UTC, sree314 approved these changes

2023-11-06 14:12 UTC, merged